=== GameFeeder/GameFeeder/config/schemas/game_config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "color": {
      "type": "string",
      "format": "color-hex"
    },
    "icon": {
      "type": "string"
    },
    "telegramIVTemplates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "domain": {
            "type": "string"
          },
          "templateHash": {
            "type": "string"
          }
        }
      }
    },
    "providers": {
      "type": "object",
      "properties": {
        "reddit": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "urlFilters": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "subreddit": {
                "type": "string"
              },
              "users": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "titleFilter": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              }
            },
            "additionalProperties": false
          }
        },
        "steam": {
          "type": "object",
          "properties": {
            "appID": {
              "type": "number"
            },
            "feeds": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false
        },
        "rss": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "flavor": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== GameFeeder/GameFeeder/config/games/amongus.json
{
  "name": "amongus",
  "label": "Among Us",
  "aliases": ["among us", "amongus"],
  "color": "#ee1a17",
  "icon": "https://imgur.com/ey1SDhy.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "AmongUs",
        "users": []
      }
    ],
    "steam": {
      "appID": 945360,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/forager.json
{
  "name": "forager",
  "label": "Forager",
  "aliases": ["forager"],
  "color": "#ff8474",
  "icon": "https://imgur.com/tqLE7vm.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "Forager",
        "users": []
      }
    ],
    "steam": {
      "appID": 751780,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/horizonforbiddenwest.json
{
  "name": "horzionforbiddenwest",
  "label": "Horizon Forbidden West",
  "aliases": [
    "horizon forbidden west",
    "horizon forbidden west complete edition",
    "horizon forbidden west: complete edition"
  ],
  "color": "#eecad9",
  "icon": "https://imgur.com/aenhMtD.jpg",
  "providers": {
    "steam": {
      "appID": 2420110,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/skylines.json
{
  "name": "skylines",
  "label": "Cities: Skylines",
  "aliases": ["cities: skylines", "cities skylines", "cs", "c:s", "skylines"],
  "color": "#6bd5f2",
  "icon": "https://imgur.com/zRjxsWw.jpg",
  "providers": {
    "steam": { "appID": 255710, "feeds": ["steam_community_announcements"] },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/hades.json
{
  "name": "hades",
  "label": "Hades",
  "aliases": ["hades"],
  "color": "#c1454c",
  "icon": "https://imgur.com/VHWSO4y.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "HadesTheGame",
        "users": []
      }
    ],
    "steam": {
      "appID": 1145360,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/veloren.json
{
  "name": "veloren",
  "label": "Veloren",
  "aliases": ["veloren"],
  "color": "#3083a6",
  "icon": "https://imgur.com/AivHTXn.png",
  "providers": {
    "reddit": [
      {
        "subreddit": "Veloren",
        "users": []
      }
    ],
    "rss": [
      {
        "label": "Veloren Blog",
        "url": "https://veloren.net/rss.xml"
      }
    ]
  }
}

=== GameFeeder/GameFeeder/config/games/steam.json
{
  "name": "steam",
  "label": "Steam",
  "aliases": ["steam"],
  "color": "#0B5A8E",
  "icon": "https://i.imgur.com/QbzZxrC.png",
  "providers": {
    "reddit": [
      {
        "subreddit": "Steam",
        "users": [
          {
            "name": "wickedplayer494",
            "titleFilter": "update"
          }
        ]
      }
    ],
    "rss": [
      {
        "label": "Steam Blog",
        "url": "https://steamcommunity.com/games/593110/rss/",
        "flavor": "steam"
      }
    ]
  }
}

=== GameFeeder/GameFeeder/config/games/apexlegends.json
{
  "name": "apexlegends",
  "label": "Apex Legends",
  "aliases": ["apex legends", "apex"],
  "color": "#b8303e",
  "icon": "https://imgur.com/AbF7UW5.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "apexlegends",
        "users": []
      }
    ],
    "steam": {
      "appID": 1172470,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}
