=== GameFeeder/GameFeeder/config/schemas/game_config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "color": {
      "type": "string",
      "format": "color-hex"
    },
    "icon": {
      "type": "string"
    },
    "telegramIVTemplates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "domain": {
            "type": "string"
          },
          "templateHash": {
            "type": "string"
          }
        }
      }
    },
    "providers": {
      "type": "object",
      "properties": {
        "reddit": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "urlFilters": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "subreddit": {
                "type": "string"
              },
              "users": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "titleFilter": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              }
            },
            "additionalProperties": false
          }
        },
        "steam": {
          "type": "object",
          "properties": {
            "appID": {
              "type": "number"
            },
            "feeds": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false
        },
        "rss": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "flavor": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== GameFeeder/GameFeeder/config/games/deadcells.json
{
  "name": "deadcells",
  "label": "Dead Cells",
  "aliases": ["dead cells", "dc", "cells"],
  "color": "#e02713",
  "icon": "https://imgur.com/pBgwuv6.png",
  "providers": {
    "reddit": [
      {
        "subreddit": "DeadCells",
        "users": []
      }
    ],
    "steam": {
      "appID": 588650,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/valheim.json
{
  "name": "valheim",
  "label": "Valheim",
  "aliases": ["valheim"],
  "color": "#b62411",
  "icon": "https://imgur.com/lEc7zOO.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "valheim",
        "users": []
      }
    ],
    "steam": {
      "appID": 892970,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/deadbydaylight.json
{
  "name": "deadbydaylight",
  "label": "Dead by Daylight",
  "aliases": ["dead by daylight", "dbd"],
  "color": "#212121",
  "icon": "https://imgur.com/fVn0tRs.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "deadbydaylight",
        "users": []
      }
    ],
    "steam": {
      "appID": 381210,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/cs.json
{
  "name": "cs",
  "label": "Cities: Skylines",
  "aliases": [
    "cities: skylines",
    "cities skylines",
    "cs",
    "c:s",
    "skylines"
  ],
  "color": "#6bd5f2",
  "icon": "https://imgur.com/zRjxsWw.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "CitiesSkylines",
        "users": []
      }
    ],
    "steam": {
      "appID": 255710,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/cp2077.json
{
  "name": "cp2077",
  "label": "Cyberpunk 2077",
  "aliases": [
    "cp2077",
    "cp",
    "2077",
    "cyberpunk 2077"
  ],
  "color": "#f3ea12",
  "icon": "https://imgur.com/rKu7F5P.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "cyberpunkgame",
        "users": []
      }
    ],
    "steam": {
      "appID": 1091500,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/pubg.json
{
  "name": "pubg",
  "label": "PLAYERUNKNOWN'S BATTLEGROUNDS",
  "aliases": [
    "playerunknown's battlegrounds",
    "playerunknowns battlegrounds",
    "pubattlegrounds",
    "battlegrounds",
    "pubg"
  ],
  "color": "#fad234",
  "icon": "https://imgur.com/Emx9o83.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "PUBATTLEGROUNDS",
        "users": []
      }
    ],
    "steam": {
      "appID": 578080,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/artifact.json
{
  "name": "artifact",
  "label": "Artifact",
  "aliases": ["artifact", "card game", "dcg"],
  "color": "#FFD700",
  "icon": "https://i.imgur.com/DblOFap.png",
  "providers": {
    "reddit": [
      {
        "subreddit": "Artifact",
        "users": [
          {
            "name": "Magesunite",
            "titleFilter": "Artifact Update"
          },
          {
            "name": "SirBelvedere",
            "titleFilter": "Artifact Update"
          },
          {
            "name": "wykrhm",
            "titleFilter": ".*"
          }
        ]
      }
    ],
    "steam": {
      "appID": 1269260,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/gta5.json
{
  "name": "gta5",
  "label": "Grand Theft Auto V",
  "aliases": ["gta5", "gtav", "gta 5", "gta v", "grand theft auto v", "grand theft auto 5"],
  "color": "#497c2d",
  "icon": "https://imgur.com/XiGyunR.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "GrandTheftAutoV",
        "users": []
      }
    ],
    "steam": {
      "appID": 271590,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}
