=== GameFeeder/GameFeeder/config/schemas/game_config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "color": {
      "type": "string",
      "format": "color-hex"
    },
    "icon": {
      "type": "string"
    },
    "telegramIVTemplates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "domain": {
            "type": "string"
          },
          "templateHash": {
            "type": "string"
          }
        }
      }
    },
    "providers": {
      "type": "object",
      "properties": {
        "reddit": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "urlFilters": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "subreddit": {
                "type": "string"
              },
              "users": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "titleFilter": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": false
                }
              }
            },
            "additionalProperties": false
          }
        },
        "steam": {
          "type": "object",
          "properties": {
            "appID": {
              "type": "number"
            },
            "feeds": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "additionalProperties": false
        },
        "rss": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "flavor": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== GameFeeder/GameFeeder/config/games/gwent.json
{
  "name": "gwent",
  "label": "GWENT: The Witcher Card Game",
  "aliases": ["gwent: the witcher card game", "gwent", "witcher card game"],
  "color": "#60ebeb",
  "icon": "https://imgur.com/8JEYta8.jpg",
  "providers": {
    "steam": {
      "appID": 1284410,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/flightsim.json
{
  "name": "flightsim",
  "label": "Microsoft Flight Simulator 2020",
  "aliases": [
    "microsoft flight simulator 2020",
    "microsoft flight simulator",
    "flight simulator 2020",
    "flightsim 2020",
    "flightsim",
    "msfs2020",
    "msfs",
    "fs"
  ],
  "color": "#5bcff5",
  "icon": "https://imgur.com/VLPzilS.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "flightsim",
        "users": []
      }
    ],
    "steam": {
      "appID": 1250410,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/ror2.json
{
  "name": "ror2",
  "label": "Risk of Rain 2",
  "aliases": ["risk of rain 2", "risk of rain", "ror", "ror2", "ror 2"],
  "color": "#a9e4e9",
  "icon": "https://imgur.com/oQhrK1N.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "ror2",
        "users": []
      }
    ],
    "steam": {
      "appID": 632360,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/rainbow6.json
{
  "name": "rainbow6",
  "label": "Tom Clancy's Rainbow Six Siege",
  "aliases": [
    "tom clancy's rainbow six siege",
    "tom clancys rainbow six siege",
    "rainbow six siege",
    "rainbow 6 siege",
    "rainbow 6",
    "rainbow6",
    "six siege",
    "6 siege",
    "tcrss",
    "rss"
  ],
  "color": "#eeeeee",
  "icon": "https://imgur.com/CtLj8WV.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "Rainbow6",
        "users": []
      }
    ],
    "steam": {
      "appID": 359550,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/teamfightmanager.json
{
  "name": "teamfight",
  "label": "Teamfight Manager",
  "aliases": ["teamfight", "teamfight manager", "tm"],
  "color": "#f8f02b",
  "icon": "https://i.imgur.com/OilT7c5.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "teamfightmanager",
        "users": []
      }
    ],
    "steam": {
      "appID": 1372810,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/helldivers2.json
{
  "name": "helldivers2",
  "label": "Helldivers 2",
  "aliases": ["helldivers 2", "helldivers2", "helldivers"],
  "color": "#dcbe2d",
  "icon": "https://imgur.com/ZjSuoLl.jpg",
  "providers": {
    "steam": {
      "appID": 553850,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/seaofthieves.json
{
  "name": "seaofthieves",
  "label": "Sea of Thieves",
  "aliases": ["sea of thieves", "sot"],
  "color": "#00ffa8",
  "icon": "https://imgur.com/4nPhHjX.jpg",
  "providers": {
    "reddit": [
      {
        "subreddit": "Seaofthieves",
        "users": []
      }
    ],
    "steam": {
      "appID": 1172620,
      "feeds": ["steam_community_announcements"]
    },
    "rss": []
  }
}

=== GameFeeder/GameFeeder/config/games/ageofempires4.json
{
  "name": "ageofempires4",
  "label": "Age of Empires IV",
  "aliases": ["age of empires iv", "age of empires 4", "aoeiv", "aoe4", "aoe iv", "aoe 4"],
  "color": "#ebc594",
  "icon": "https://imgur.com/NCYubeG.jpg",
  "providers": {
    "steam": {
      "appID": 1466860,
      "feeds": ["steam_community_announcements"]
    },
    "reddit": [
      {
        "subreddit": "aoe4",
        "users": []
      }
    ],
    "rss": []
  }
}
